In [92]:
"""Задание 1
Необходимо построить модели логистической регрессии и SVM, которые предсказывает уровень дохода человека.
Вывести качество полученных моделей на тестовой выборке, используя функцию score у модели
"""

import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
# from sklearn.metrics import r2_score
from sklearn import svm
import matplotlib.pyplot as plt
from matplotlib import colors

data = pd.read_csv('adult.csv')
data.head()

data.columns = (['age/возраст',                                 # 'Возраст',
                'workclass/рабочий класс',                      # 'Рабочий класс (частный, Self-emp-not-inc, Self-emp-inc, 
                                                                   # федеральное правительство, проч.)', 
                'fnlwgt/кол-во людей',                          # 'final weight) – примерная оценка количества людей, 
                                                                   # которое представляет каждая строка данных',
                'education/образование',                        # 'Образование (бакалавриат, Some-College, 11, HS, Prof-school)',   
                'educational-num/длительность обучения',        # 'Пульс (норм 30-40)',
                'marital-status/семейный статус',               # 'Семейный статус (женат-гражданский-супруг, разведен, 
                                                                   #не был в браке и проч.)', 
                'occupation/род занятий',                       # 'Род занятий (Техподдержка, Ремесло-ремонт, Другое-обслуживание, 
                                                                   # Продажи и проч.)',
                'relationship/родственные связи',               # 'Отношения (Жена, Собственный ребенок, Муж, Не в семье и проч.)'
                'race/Раса',                                    # 'Раса (белая, азиатско-тихоокеанская, американская-индийская-эскимосская, 
                                                                   # другая, черная)',
                'gender/пол',                                   # 'Пол (женский, мужской)'
                'capital-gain/прирост капитала',                # 'Прирост капитала (непрерывная величина)',
                'capital-loss/убыток капитала',                 # 'Убыток капитала (непрерывная величина)'
                'hours-per-week/часов в неделю',                # 'Часов в неделю (непрерывная величина)',
                'native-country/страна происхождения',          # 'Родная страна (США, Камбоджа, Англия и проч.)'
                'income/доход'])                                # 'Доход (> 50K, <= 50K)'
data.tail()

age/возраст workclass/рабочий класс  fnlwgt/кол-во людей  \
48837           27                 Private               257302   
48838           40                 Private               154374   
48839           58                 Private               151910   
48840           22                 Private               201490   
48841           52            Self-emp-inc               287927   

      education/образование  educational-num/длительность обучения  \
48837            Assoc-acdm                                     12   
48838               HS-grad                                      9   
48839               HS-grad                                      9   
48840               HS-grad                                      9   
48841               HS-grad                                      9   

      marital-status/семейный статус occupation/род занятий  \
48837             Married-civ-spouse           Tech-support   
48838             Married-civ-spouse      Machine-op-inspct   
48839                        Widowed           Adm-clerical   
48840                  Never-married           Adm-clerical   
48841             Married-civ-spouse        Exec-managerial   

      relationship/родственные связи race/Раса gender/пол  \
48837                           Wife     White     Female   
48838                        Husband     White       Male   
48839                      Unmarried     White     Female   
48840                      Own-child     White       Male   
48841                           Wife     White     Female   

       capital-gain/прирост капитала  capital-loss/убыток капитала  \
48837                              0                             0   
48838                              0                             0   
48839                              0                             0   
48840                              0                             0   
48841                          15024                             0   

       hours-per-week/часов в неделю native-country/страна происхождения  \
48837                             38                       United-States   
48838                             40                       United-States   
48839                             40                       United-States   
48840                             20                       United-States   
48841                             40                       United-States   

      income/доход  
48837        <=50K  
48838         >50K  
48839        <=50K  
48840        <=50K  
48841         >50K

In [93]:
# исследуем модель зависимости уровня дохода от пола человека 
model_1 = LogisticRegression()
le = LabelEncoder() 
# le.fit_transform(data['income/доход'])
X = pd.get_dummies(data.loc[:, ['gender/пол']])
y = pd.Series(data = le.fit_transform(data['income/доход']))
# разделим данные на 2 выборки: для обучения (50 процентов) и тестирования обученной модели (50 процентов):
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)
# print('Размер X_train: ', X_train.shape)
# print('Размер X_test: ', X_test.shape)
# print('Размер y_train: ', y_train.shape)
# print('Размер y_test: ', y_test.shape)

In [94]:
model_1.fit(X_train, y_train)            # обучаем модель 
y_pred = model_1.predict(X_test)         # формируем прогнозные значения
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [95]:
# # смотрим разницу факта и прогноза
result = pd.DataFrame([y_test, y_pred]).T
                      
result.head(10)

0    1
7762   0.0  0.0
23881  0.0  0.0
30507  1.0  NaN
28911  0.0  NaN
19484  0.0  0.0
43031  0.0  NaN
28188  0.0  NaN
12761  1.0  0.0
40834  0.0  NaN
27875  0.0  NaN

In [96]:
# Рассчитаем коэффициент детерминации, демонстрирующий нам уровень ошибки прогноза
# получаем ошибку в половне случаев

model_1.score(X_test, y_test)  

0.7629089717865771

In [102]:
# реализуем метод опорных векторов 
clf = svm.SVC()
clf.fit(X_train, y_train)   


SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [106]:
y_pred_clf = clf.predict(X_test)         # формируем прогнозные значения в методе опорных векторов
y_pred_clf

array([0, 0, 0, ..., 0, 0, 0])

In [107]:
clf.score(X_test, y_test)  

0.7811309938167971

In [111]:
# исследуем модель зависимости уровня дохода от образования
model_2 = LogisticRegression()
# целевая переменная (столбец 'income/доход') является категориальной
# переведем значения этой колонки в числа, оставив один столбец
le = LabelEncoder() 
# le.fit_transform(data['income/доход'])
X = pd.get_dummies(data.loc[:, ['education/образование']])
y = pd.Series(data = le.fit_transform(data['income/доход']))
# разделим данные на 2 выборки: для обучения (50 процентов) и тестирования обученной модели (50 процентов):
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)


In [112]:
model_2.fit(X_train, y_train)            # обучаем модель 
y_pred = model_2.predict(X_test)         # формируем прогнозные значения
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [113]:
# Рассчитаем коэффициент детерминации, демонстрирующий нам уровень ошибки прогноза
# получаем ошибку в половне случаев

model_2.score(X_test, y_test) 

0.7811309938167971

In [114]:
# реализуем метод опорных векторов для зависимости уровня дохода от образования 
clf = svm.SVC()
clf.fit(X_train, y_train) 

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [115]:
y_pred_clf = clf.predict(X_test)         # формируем прогнозные значения в методе опорных векторов
y_pred_clf

array([0, 0, 0, ..., 0, 0, 0])

In [116]:
clf.score(X_test, y_test)  

0.7811309938167971