In [1]:
"""Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))"""

import numpy as np

a = np.array(range(10))
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [2]:
"""Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали"""

import numpy as np

a = np.diag(np.arange(10, 2, -2))
print(a)
print(np.sum(a))


[[10  0  0  0]
 [ 0  8  0  0]
 [ 0  0  6  0]
 [ 0  0  0  4]]
28


In [3]:
"""Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3"""

from numpy import linalg
a = np.array([[4, 2, 1], [1, 3, 0], [5, 4, 0]])
b = np.array([4, 12, -3])
print(linalg.solve(a, b))

print(np.allclose(np.dot(a, linalg.solve(a,b)), b))


[-5.18181818  5.72727273 13.27272727]
True


In [1]:
"""Имеется база покупок Интернет-магазина. Столбец А - ID пользователя, остальные столбцы - 
количество покупок категорий товаров, совершенных данными пользователями. 
Найдите самого похожего пользователя. 
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива user_stats
"""
import numpy as np
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

next_user_stats = np.array([0, 1, 2, 0, 0, 0])




similarity=[]
next_user_stats_lenght = np.linalg.norm(next_user_stats)

# перебираем циклом массив:
for line in users_stats:
    users_stats_lenght = np.linalg.norm(line)              
    
    # заполняем пустой список элементами: 
    # элементы similarity - это косинусное сходство каждого покупателя из users_stats с новым покупателем next_user_stats:
    new_items = similarity.append(round((np.dot(line, next_user_stats)/(users_stats_lenght*next_user_stats_lenght)), 2))
print(similarity)


[0.2, 0.85, 0.4, 0.79, 0.4, 0.0, 0.0, 0.95, 0.0, 0.0]
