In [1]:
"""Уровень 0:
Создайте матрицу 3 на 3, заполненную числами от 1 до 9
Прибавьте к ней матрицу с единицами на диагонале
Умножьте полученную матрицу на вектор (1, 2, 3)
Посчитайте обратную матрицу к полученной матрице
"""

import numpy as np
import matplotlib.pyplot as plt
import math

m_sqr = [[1., 2., 3.], [4., 5., 6.], [7., 8., 9.]]
m_sqr_arr = np.array(m_sqr)
m_sqr_arr

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [2]:
m_ones_arr = np.eye(3)
m_sum_arr = m_sqr_arr + m_ones_arr # добавляем к матрице единичную матрицу
m_sum_arr

array([[ 2.,  2.,  3.],
       [ 4.,  6.,  6.],
       [ 7.,  8., 10.]])

In [8]:
v_1 = [1,2,3]
m_mult_arr_dot = np.dot(m_sum_arr, v_1) # полученную матрицу умножаем на вектор 
m_mult_arr_dot

array([15., 34., 53.])

In [19]:
m_mult_arr = np.dot(m_sum_arr,v_1)
m_mult_arr

array([15., 34., 53.])

In [28]:
m_converse_arr = np.linalg.inv(m_sum_arr) # к полученной матрице считаем обратную ей 
np.round(m_converse_arr, 2)


array([[-6. , -2. ,  3. ],
       [-1. ,  0.5,  0. ],
       [ 5. ,  1. , -2. ]])

In [30]:
check_matrix = np.dot(m_converse_arr, m_sum_arr) # проверяем: обратную матрицу перемножаем с иходной - 
                                                #должны получить матрицу с единицами на главной диагонали
np.round(check_matrix, 4)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
"""Уровень 1:
Дан объект в 2d пространстве.
При помощи матричных операций выполните:

Уменьшить объект в два раза
Повернуть на 130 градусов
Отразить объект относительно прямой y=x
Выполнить смещение объекта и масштабирование (применить 2 матрицы трансформаций). 
Смещение на (200, 300) и масштабирование на (0.5, 1.2)
"""

A = [
[-100, -100, 1],  # Третье - по оси z, просто принято задавать в трёх измерениях, можно убрать 3-е значение, график не изменится
[-100, 100, 1],   # третье число матрицы - координата Z (здесь она никак не влияет на результат)
[100, 100, 1],
[0, 0, 1],
[100, -100, 1],
[-100, -100, 1]
]

A = np.array(A)
x = A[:,0]   # Собираем значения координат, по которым строим plot-визуализацию
y = A[:,1]

plt.plot(x, y)
plt.ylim([-200, 200])
plt.xlim([-200, 200])



In [ ]:
# Можно сделать так: 
#     1) A = A * 0.5 или A = A / 2
#     2) plt.plot(x*0.5, y*0.5)
# Однако мы выполним действие через трансформирующую матрицу 

B = np.array([
[0.5, 0, 0],
[0, 0.5, 0],
[0, 0, 0.5],
])


reduce_2_times = A@B       # reduce_2_times = np.dot(A,B)
x = reduce_2_times[:,0]
y = reduce_2_times[:,1]

plt.plot(x, y)
plt.ylim([-200, 200])
plt.xlim([-200, 200])
reduce_2_times

In [ ]:
# повернем объект на 130 градусов

C = np.array([
[math.cos(math.radians(130)), math.sin(math.radians(130))],
[math.sin(math.radians(130)), math.cos(math.radians(130))],
[0,0]
])

rotation_matrix = A@C 


x = rotation_matrix[:,0]
y = rotation_matrix[:,1]

plt.plot(x, y)
plt.ylim([-200, 200])
plt.xlim([-200, 200])
rotation_matrix